Importing packages

In [245]:
import pandas as pd
import requests
import json
import datetime
import matplotlib
%matplotlib inline

In [246]:
dict_lat_long = {'Buenos Aires': ['-34.61315', '-58.37723', '-03:00'],
                 'Cancun': ['21.1742897', '-86.8465576', '-05:00'],
                 'Rio de Janeiro': ['-22.90278', '-43.2075', '-03:00']}

In [343]:
def weather_dep():

    # Ask for inputs
    
    city = str(input('What is you destination:'))
    departure_date = str(input('When do you want to go (YYYY-MM-DD):'))
    days = int(input('How long do you want to stay:'))    
    
    # Create a list of dates to search for weather info
    
    years_hist = 3
    departure_list = departure_date.split('-')
    departure_day = datetime.date(year=int(departure_list[0]), month=int(departure_list[1]), day=int(departure_list[2]))
    date_list = [str(departure_day.replace(year=int(departure_list[0])-(y+1)) + datetime.timedelta(days=x)) for x in range(days) for y in range(years_hist)]
    
    # Create an empty DataFrame with the desired columns
    
    column_name = ['id','city','departure date', 'lower temperature', 'higher temperature', 'rain probability', 'weather condition']
    df_weather = pd.DataFrame(columns= column_name)
    
    # For loop to append the daily weather to the empty DataFrame
#    for c in city:        
    for period in date_list:
        url_base = f'https://api.darksky.net/forecast/5c060fde06e54a7eb56d4fbbce7dbd8f/{dict_lat_long[city][0]},{dict_lat_long[city][1]},{period}T00:00:00{dict_lat_long[city][2]}?units=ca&?exclude=currently,flags'
        headers = {'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                   'Accept-Encoding': 'gzip, deflate, br',
                   'Accept-Language': 'de,en-US;q=0.7,en;q=0.3',
                   'Connection': 'keep-alive',
                   'Host': 'api.darksky.net',
                   'Referer': 'https://darksky.net/dev/account',
                   'TE': 'Trailers',
                   'Upgrade-Insecure-Requests': '1',
                   'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0'}
        r = requests.get(url_base, headers)
        row_list = pd.Series([str(city + '_' + departure_date), city, departure_date, r.json()['daily']['data'][0]['temperatureLow'], r.json()['daily']['data'][0]['temperatureHigh'], r.json()['daily']['data'][0]['precipProbability'],r.json()['daily']['data'][0]['summary']], index=column_name)
        df_weather = df_weather.append(row_list, ignore_index=True)
        row_list = row_list.drop(column_name)
    return df_weather

Creating DFs for Rio de Janeiro

In [344]:
df_rio_de_janeiro_1 = weather_dep()

What is you destination:Rio de Janeiro
When do you want to go (YYYY-MM-DD):2019-12-21
How long do you want to stay:7

In [345]:
df_rio_de_janeiro_2 = weather_dep()

What is you destination:Rio de Janeiro
When do you want to go (YYYY-MM-DD):2020-01-18
How long do you want to stay:7

In [346]:
df_rio_de_janeiro_3 = weather_dep()

What is you destination:Rio de Janeiro
When do you want to go (YYYY-MM-DD):2020-02-22
How long do you want to stay:7

In [347]:
df_rio_de_janeiro_1.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Rio de Janeiro_2019-12-21,Rio de Janeiro,2019-12-21,25.82,32.97,0.12,Humid throughout the day.
1,Rio de Janeiro_2019-12-21,Rio de Janeiro,2019-12-21,22.42,31.70,0.00,Humid and partly cloudy throughout the day.
2,Rio de Janeiro_2019-12-21,Rio de Janeiro,2019-12-21,22.83,32.50,0.00,Clear throughout the day.
3,Rio de Janeiro_2019-12-21,Rio de Janeiro,2019-12-21,25.07,35.02,0.15,Humid and partly cloudy throughout the day.
4,Rio de Janeiro_2019-12-21,Rio de Janeiro,2019-12-21,23.63,29.11,0.00,Humid and mostly cloudy throughout the day.

In [348]:
df_rio_de_janeiro_2.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Rio de Janeiro_2020-01-18,Rio de Janeiro,2020-01-18,25.81,33.04,0.17,Humid throughout the day.
1,Rio de Janeiro_2020-01-18,Rio de Janeiro,2020-01-18,26.60,37.32,0.00,Humid throughout the day.
2,Rio de Janeiro_2020-01-18,Rio de Janeiro,2020-01-18,25.34,36.10,0.00,Humid throughout the day.
3,Rio de Janeiro_2020-01-18,Rio de Janeiro,2020-01-18,26.56,35.84,0.41,Humid and partly cloudy throughout the day.
4,Rio de Janeiro_2020-01-18,Rio de Janeiro,2020-01-18,24.79,34.85,0.00,Humid throughout the day.

In [349]:
df_rio_de_janeiro_3.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Rio de Janeiro_2020-02-22,Rio de Janeiro,2020-02-22,25.17,34.03,0.29,Humid throughout the day.
1,Rio de Janeiro_2020-02-22,Rio de Janeiro,2020-02-22,23.79,31.29,0.00,Humid and partly cloudy throughout the day.
2,Rio de Janeiro_2020-02-22,Rio de Janeiro,2020-02-22,23.56,33.56,0.00,Clear throughout the day.
3,Rio de Janeiro_2020-02-22,Rio de Janeiro,2020-02-22,27.17,36.43,0.24,Humid and partly cloudy throughout the day.
4,Rio de Janeiro_2020-02-22,Rio de Janeiro,2020-02-22,22.84,26.45,0.00,Humid throughout the day.

Creating DFs for Buenos Aires

In [351]:
df_buenos_aires_1 = weather_dep()

What is you destination:Buenos Aires
When do you want to go (YYYY-MM-DD):2019-12-21
How long do you want to stay:7

In [352]:
df_buenos_aires_2 = weather_dep()

What is you destination:Buenos Aires
When do you want to go (YYYY-MM-DD):2020-01-18
How long do you want to stay:7

In [353]:
df_buenos_aires_3 = weather_dep()

What is you destination:Buenos Aires
When do you want to go (YYYY-MM-DD):2020-02-22
How long do you want to stay:7

In [354]:
df_buenos_aires_1.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Buenos Aires_2019-12-21,Buenos Aires,2019-12-21,18.30,27.06,0.15,Partly cloudy throughout the day.
1,Buenos Aires_2019-12-21,Buenos Aires,2019-12-21,23.55,31.57,0.00,Humid and mostly cloudy throughout the day.
2,Buenos Aires_2019-12-21,Buenos Aires,2019-12-21,20.30,34.77,0.00,Clear throughout the day.
3,Buenos Aires_2019-12-21,Buenos Aires,2019-12-21,18.72,25.23,0.07,Partly cloudy throughout the day.
4,Buenos Aires_2019-12-21,Buenos Aires,2019-12-21,19.33,32.66,0.00,Humid and partly cloudy throughout the day.

In [355]:
df_buenos_aires_2.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Buenos Aires_2020-01-18,Buenos Aires,2020-01-18,15.38,23.33,0.62,Possible drizzle in the morning.
1,Buenos Aires_2020-01-18,Buenos Aires,2020-01-18,20.54,31.69,0.00,Partly cloudy throughout the day.
2,Buenos Aires_2020-01-18,Buenos Aires,2020-01-18,22.93,29.89,0.00,Clear throughout the day.
3,Buenos Aires_2020-01-18,Buenos Aires,2020-01-18,19.44,24.13,0.07,Partly cloudy throughout the day.
4,Buenos Aires_2020-01-18,Buenos Aires,2020-01-18,21.11,32.75,0.00,Clear throughout the day.

In [356]:
df_buenos_aires_3.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Buenos Aires_2020-02-22,Buenos Aires,2020-02-22,22.30,32.17,0.72,Rain in the evening and overnight.
1,Buenos Aires_2020-02-22,Buenos Aires,2020-02-22,17.78,27.40,0.00,Clear throughout the day.
2,Buenos Aires_2020-02-22,Buenos Aires,2020-02-22,23.78,32.35,0.00,Humid and partly cloudy throughout the day.
3,Buenos Aires_2020-02-22,Buenos Aires,2020-02-22,18.30,25.49,0.98,Light rain and humid throughout the day.
4,Buenos Aires_2020-02-22,Buenos Aires,2020-02-22,18.27,28.34,0.00,Clear throughout the day.

Creating DFs for Cancun

In [357]:
df_cancun_1 = weather_dep()

What is you destination:Cancun
When do you want to go (YYYY-MM-DD):2019-12-21
How long do you want to stay:7

In [363]:
df_cancun_2 = weather_dep()

What is you destination:Cancun
When do you want to go (YYYY-MM-DD):2020-01-18
How long do you want to stay:7

In [359]:
df_cancun_3 = weather_dep()

What is you destination:Cancun
When do you want to go (YYYY-MM-DD):2020-02-22
How long do you want to stay:7

In [364]:
df_cancun_1.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Cancun_2019-12-21,Cancun,2019-12-21,14.60,24.99,0.08,Clear throughout the day.
1,Cancun_2019-12-21,Cancun,2019-12-21,24.14,29.77,0.00,Humid and mostly cloudy throughout the day.
2,Cancun_2019-12-21,Cancun,2019-12-21,23.28,28.38,0.00,Partly cloudy throughout the day.
3,Cancun_2019-12-21,Cancun,2019-12-21,15.62,25.79,0.09,Clear throughout the day.
4,Cancun_2019-12-21,Cancun,2019-12-21,19.76,29.46,0.00,Partly cloudy throughout the day.

In [365]:
df_cancun_2.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Cancun_2020-01-18,Cancun,2020-01-18,22.13,27.92,0.15,Mostly cloudy throughout the day.
1,Cancun_2020-01-18,Cancun,2020-01-18,19.57,23.34,0.00,Mostly cloudy throughout the day.
2,Cancun_2020-01-18,Cancun,2020-01-18,22.99,28.20,0.00,Partly cloudy throughout the day.
3,Cancun_2020-01-18,Cancun,2020-01-18,21.62,29.09,0.13,Partly cloudy throughout the day.
4,Cancun_2020-01-18,Cancun,2020-01-18,17.27,23.36,0.00,Overcast throughout the day.

In [366]:
df_cancun_3.head()

,id,city,departure date,lower temperature,higher temperature,rain probability,weather condition
0,Cancun_2020-02-22,Cancun,2020-02-22,24.55,30.69,0.18,Humid and partly cloudy throughout the day.
1,Cancun_2020-02-22,Cancun,2020-02-22,22.70,28.32,0.00,Humid and mostly cloudy throughout the day.
2,Cancun_2020-02-22,Cancun,2020-02-22,17.01,29.20,0.00,Partly cloudy throughout the day.
3,Cancun_2020-02-22,Cancun,2020-02-22,24.69,29.80,0.18,Humid and partly cloudy throughout the day.
4,Cancun_2020-02-22,Cancun,2020-02-22,24.63,28.35,0.00,Humid and partly cloudy throughout the day.

Merging DFs

In [367]:
list_rio = [df_rio_de_janeiro_1, df_rio_de_janeiro_2, df_rio_de_janeiro_3]

In [368]:
df_rio_final = pd.concat(list_rio, ignore_index=True)
len(df_rio_final)

63

In [369]:
list_buenos = [df_buenos_aires_1, df_buenos_aires_2, df_buenos_aires_3]

In [370]:
df_buenos_final = pd.concat(list_buenos, ignore_index=True)

In [371]:
len(df_rio_final)

63

In [372]:
list_cancun = [df_cancun_1, df_cancun_2, df_cancun_3]

In [373]:
df_cancun_final = pd.concat(list_cancun, ignore_index=True)
len(df_cancun_final)

63

In [374]:
list_destination = [df_buenos_final, df_cancun_final, df_rio_final]

In [375]:
df_destination_total = pd.concat(list_destination, ignore_index=True)
len(df_destination_total)

189

In [376]:
destination_summary = df_destination_total.groupby(by='id').mean().reset_index()
destination_summary['rain probability'] = destination_summary['rain probability']*100
destination_summary

,id,lower temperature,higher temperature,rain probability
0,Buenos Aires_2019-12-21,20.465238,28.860000,8.428571
1,Buenos Aires_2020-01-18,21.216190,29.919048,8.428571
2,Buenos Aires_2020-02-22,19.848095,28.323810,9.904762
3,Cancun_2019-12-21,20.674762,28.191905,8.142857
4,Cancun_2020-01-18,20.995714,27.426667,13.714286
5,Cancun_2020-02-22,22.418571,29.291429,6.476190
6,Rio de Janeiro_2019-12-21,24.198571,32.266667,13.285714
7,Rio de Janeiro_2020-01-18,25.236667,33.646667,7.190476
8,Rio de Janeiro_2020-02-22,24.160952,31.777619,14.428571

In [330]:
destination_summary.to_csv('weather_summary')

In [384]:
weather_summary = df_destination_total.groupby(by=['id','weather condition']).count().reset_index()
weather_summary

,id,weather condition,city,departure date,lower temperature,higher temperature,rain probability
0,Buenos Aires_2019-12-21,Clear throughout the day.,8,8,8,8,8
1,Buenos Aires_2019-12-21,Humid and mostly cloudy throughout the day.,2,2,2,2,2
2,Buenos Aires_2019-12-21,Humid and partly cloudy throughout the day.,1,1,1,1,1
3,Buenos Aires_2019-12-21,Humid throughout the day.,1,1,1,1,1
4,Buenos Aires_2019-12-21,Mostly cloudy throughout the day.,2,2,2,2,2
...,...,...,...,...,...,...,...
56,Rio de Janeiro_2020-02-22,Humid throughout the day.,3,3,3,3,3
57,Rio de Janeiro_2020-02-22,Light rain in the evening and overnight.,1,1,1,1,1
58,Rio de Janeiro_2020-02-22,"Light rain until morning, starting again in th...",1,1,1,1,1
59,Rio de Janeiro_2020-02-22,Mostly cloudy throughout the day.,3,3,3,3,3
60,Rio de Janeiro_2020-02-22,Possible light rain in the evening.,1,1,1,1,1

In [386]:
weather_summary = weather_summary[['id', 'weather condition', 'city']]

,id,weather condition,city
0,Buenos Aires_2019-12-21,Clear throughout the day.,8
1,Buenos Aires_2019-12-21,Humid and mostly cloudy throughout the day.,2
2,Buenos Aires_2019-12-21,Humid and partly cloudy throughout the day.,1
3,Buenos Aires_2019-12-21,Humid throughout the day.,1
4,Buenos Aires_2019-12-21,Mostly cloudy throughout the day.,2
...,...,...,...
56,Rio de Janeiro_2020-02-22,Humid throughout the day.,3
57,Rio de Janeiro_2020-02-22,Light rain in the evening and overnight.,1
58,Rio de Janeiro_2020-02-22,"Light rain until morning, starting again in th...",1
59,Rio de Janeiro_2020-02-22,Mostly cloudy throughout the day.,3
60,Rio de Janeiro_2020-02-22,Possible light rain in the evening.,1

In [392]:
weather_summary.to_csv('weather_condition')